name: PR Links

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build site
        uses: iciaran/astro-action@e27f233ebaca2f3d8780439c79c022d336044b75

        with:
          package-manager: pnpm@latest
          node-version: 24.13